# Generated by Django 3.1.3 on 2020-11-25 18:34

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='model',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
