# Generated by Django 3.1.3 on 2020-11-24 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('feature1', models.IntegerField()),
                ('feature2', models.IntegerField()),
                ('feature3', models.IntegerField()),
                ('feature4', models.IntegerField()),
                ('feature5', models.IntegerField()),
                ('feature6', models.IntegerField()),
                ('feature7', models.IntegerField()),
                ('feature8', models.IntegerField()),
                ('feature9', models.IntegerField()),
                ('feature10', models.IntegerField()),
                ('feature11', models.IntegerField()),
                ('feature12', models.IntegerField()),
                ('feature13', models.IntegerField()),
                ('feature14', models.IntegerField()),
                ('feature15', models.IntegerField()),
                ('feature16', models.IntegerField()),
                ('feature17', models.IntegerField()),
                ('feature18', models.IntegerField()),
                ('feature19', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
